title: My daily blog 
email: wonchang.k@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings
author: wonchangkim # add your name
author-pic: githublogo.jpg
author-logo: logoblack.png
about-author: 많이 하면 할수록 많이 할수 있다.

# Contact links
email: wonchang.k@gmail.com
website: wonchangkim.github.io/
github: wonchangkim


# Newsletter
mailchimp: # Add your MailChimp form identifier.

# Disqus
discus_identifier: wonchangkim # Add your discus identifier

# Tracker
analytics: # Google Analytics

# Paginate
paginate: 10
paginate_path: /page:num/

# Build settings
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
